name: 'soccer_analysis'
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython>=7.15
  - matplotlib>=3.2.2
  - scikit-learn>=1.1.3
  - requests>=2.24.0
  - graphviz
  - python-graphviz
  - eli5
  - shap
  - jinja2
  - altair
  - altair_saver
  - selenium<4.3.0
  - pandas<1.5
  - imbalanced-learn
  - pip
  - lightgbm
  - openpyxl
  - pytest
  - pip:
    - joblib==1.1.0
    - mglearn
    - psutil>=5.7.2
    - docopt-ng
    - dill
    - pycodestyle
    - autopep8
